// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cart.Models
{
    [Table("userCart")]
    public partial class userCart
    {
        [Key]
        public int userID { get; set; }
        public List<item> Items { get; set; }
    }
}