// <auto-generated />
using System;
using Cart.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cart.Migrations
{
    [DbContext(typeof(CartContext))]
    [Migration("20230614134725_newMig")]
    partial class newMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cart.Models.item", b =>
                {
                    b.Property<int>("itemId")
                        .HasColumnType("int");

                    b.Property<string>("itemDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("itemName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("itemPrice")
                        .HasColumnType("int");

                    b.Property<int?>("userCartuserID")
                        .HasColumnType("int");

                    b.HasKey("itemId");

                    b.HasIndex("userCartuserID");

                    b.ToTable("item");
                });

            modelBuilder.Entity("Cart.Models.userCart", b =>
                {
                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("userID");

                    b.ToTable("userCart");
                });

            modelBuilder.Entity("Cart.Models.item", b =>
                {
                    b.HasOne("Cart.Models.userCart", null)
                        .WithMany("Items")
                        .HasForeignKey("userCartuserID");
                });

            modelBuilder.Entity("Cart.Models.userCart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
